# Generated by Django 3.1.7 on 2021-03-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalText',
        ),
    ]
